name: .NET

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 5.0.x
    - name: Add Microsoft Code Coverage
      run: dotnet add package Microsoft.CodeCoverage --version 16.9.4
    - name: Restore dependencies
      run: dotnet restore project.sln
    - name: Build
      run: dotnet build project.sln --no-restore
    - name: Test
      run: dotnet test Source/Compiler.Tests --no-build --verbosity normal
